### ISSUE TITLE
Example of using the current tap 

### ISSUE THREAD

**Issue by nitingithub** [ScaleUnlimited/cascading.solr#9]
Hi, 

 Are there any examples of how to use this schema in a tap and produced lucene indices? We are trying to do this for solrcloud as well. If we get it working, we will contribute a patch for solrcloud. 

Thanks in advance, 
Nitin

**Comment by kkrugler** [comment]
I've added some example code to the `README.md` file - see https://github.com/ScaleUnlimited/cascading.solr. If that's what you need, please go ahead and close this issue, thanks.

**Comment by nitingithub** [comment]
Thanks that helps.
